### blogs
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Arto Hellas know hot to blog even better",
  "author": "Hellas",
  "url": "https://www.theworldsworstwebsiteever.com",
  "userId": "5f9e6fcfd7ddfcb123d50e12",
  "likes": 0
}

###

GET http://localhost:3003/api/blogs

### users
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Hellas",
  "name": "Arto",
  "password": "password"
}

###

GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "hellas",
  "password": "prrkl"
}